import {
  type Application,
  makeTimelineEvent,
  stageEventTitle,
} from "@/lib/applications";
import { offset } from "@/lib/dates";

export const seed: Application[] = [
  {
    id: "nory",
    company: "Nory",
    role: "Product Designer",
    jobUrl: "",
    state: "active",
    currentStage: "1st interview",
    sentiment: "good",
    timeline: [
      makeTimelineEvent(
        "applied",
        "Application submitted",
        offset(-17),
        undefined,
        "nory-applied",
      ),
      makeTimelineEvent(
        "1st interview",
        stageEventTitle("1st interview"),
        offset(-5),
        undefined,
        "nory-interview",
      ),
    ],
    fit: 4,
    appliedDate: offset(-17),
    followUpDate: offset(2),
    nextAction: "Prepare questions for Head of Product interview",
    fitEvidence:
      "B2B AI, complex workflows, product-design-engineering background.",
    risks: "Restaurant domain knowledge is new; process may be slow.",
    learning: "Make the AI collaboration and operational experience concrete.",
  },
  {
    id: "linear",
    company: "Linear",
    role: "Staff Product Designer",
    jobUrl: "",
    state: "active",
    currentStage: "applied",
    sentiment: "neutral",
    timeline: [
      makeTimelineEvent(
        "applied",
        "Application submitted",
        offset(-8),
        undefined,
        "linear-applied",
      ),
    ],
    fit: 5,
    appliedDate: offset(-8),
    followUpDate: offset(6),
    nextAction: "Send focused portfolio follow-up",
    fitEvidence:
      "Design systems, async operating model, high-bar product craft.",
    risks: "Exceptionally competitive; portfolio must carry the case.",
    learning: "",
  },
  {
    id: "checkly",
    company: "Checkly",
    role: "Product Designer",
    jobUrl: "",
    state: "closed",
    currentStage: "1st interview",
    sentiment: "bad",
    outcome: "other",
    timeline: [
      makeTimelineEvent(
        "applied",
        "Application submitted",
        offset(-32),
        undefined,
        "checkly-applied",
      ),
      makeTimelineEvent(
        "closed",
        "Closed — Other",
        offset(-20),
        undefined,
        "checkly-closed",
      ),
    ],
    fit: 4,
    appliedDate: offset(-32),
    followUpDate: "",
    nextAction: "",
    fitEvidence: "Developer tooling and design-engineering overlap.",
    risks: "Interview was cancelled without context.",
    learning: "Follow up once, then close it.",
  },
  {
    id: "example",
    company: "Example Co",
    role: "Senior Product Designer",
    jobUrl: "",
    state: "active",
    currentStage: "applied",
    sentiment: "neutral",
    timeline: [
      makeTimelineEvent(
        "applied",
        "Application submitted",
        offset(-23),
        undefined,
        "example-applied",
      ),
    ],
    fit: 2,
    appliedDate: offset(-23),
    followUpDate: "",
    nextAction: "",
    fitEvidence: "Interesting product space.",
    risks: "Weak direct evidence of fit and unclear remote policy.",
    learning: "",
  },
];
