import {
  type Application,
  type CurrentStage,
  type TimelineEvent,
  type TimelineEventType,
  makeTimelineEvent,
  prettyOutcome,
  prettySentiment,
  stageEventTitle,
} from "@/lib/applications";
import { offset } from "@/lib/dates";

const event = (
  id: string,
  type: TimelineEventType,
  days: number,
  extra?: { title?: string; note?: string },
): TimelineEvent => {
  const title =
    extra?.title ??
    (type === "on_hold"
      ? "Process on hold"
      : type === "closed"
        ? "Closed"
        : type === "note"
          ? "Note"
          : type === "sentiment"
            ? `Sentiment — ${prettySentiment("neutral")}`
            : stageEventTitle(type as CurrentStage));
  return makeTimelineEvent(type, title, offset(days), extra?.note, id);
};

export const seed: Application[] = [
  {
    id: "pebblepine",
    company: "Pebblepine",
    role: "Staff Product Designer",
    jobUrl: "https://jobs.pebblepine.example/staff-product-designer",
    state: "active",
    currentStage: "applied",
    sentiment: "good",
    timeline: [
      event("pebblepine-applied", "applied", -4),
    ],
    fit: 5,
    appliedDate: offset(-4),
    followUpDate: offset(-1),
    nextAction: "Nudge the recruiter about the take-home brief",
    fitEvidence: "Systems-heavy B2B, design-eng pairing, strong craft bar.",
    risks: "Headcount may slip a quarter.",
    learning: "",
  },
  {
    id: "northlamp",
    company: "Northlamp",
    role: "Product Designer",
    jobUrl: "https://northlamp.example/careers/product-designer",
    state: "active",
    currentStage: "1st interview",
    sentiment: "good",
    timeline: [
      event("northlamp-applied", "applied", -12),
      event("northlamp-1st", "1st interview", -3),
      event("northlamp-note", "note", -2, {
        title: "Note",
        note: "Hiring manager wants a walkthrough of a messy workflow case.",
      }),
    ],
    fit: 4,
    appliedDate: offset(-12),
    followUpDate: offset(8),
    nextAction: "Send the workflow case study before Thursday",
    fitEvidence: "Internal tools, dense tables, ops users.",
    risks: "Panel includes a sceptical eng manager.",
    learning: "",
  },
  {
    id: "kite-harbor",
    company: "Kite Harbor",
    role: "Senior Product Designer",
    jobUrl: "https://kiteharbor.example/jobs/spd",
    state: "active",
    currentStage: "2nd interview",
    sentiment: "neutral",
    timeline: [
      event("kite-applied", "applied", -28),
      event("kite-1st", "1st interview", -18),
      event("kite-2nd", "2nd interview", -9),
    ],
    fit: 3,
    appliedDate: offset(-28),
    followUpDate: "",
    nextAction: "Ping after the second-round debrief",
    fitEvidence: "Marketplace UX, trust and payments overlap.",
    risks: "No follow-up date set; process feels quiet.",
    learning: "",
  },
  {
    id: "brineware",
    company: "Brineware",
    role: "UX Designer",
    jobUrl: "",
    state: "active",
    currentStage: "3rd interview",
    sentiment: "bad",
    timeline: [
      event("brine-applied", "applied", -40),
      event("brine-1st", "1st interview", -30),
      event("brine-2nd", "2nd interview", -21),
      event("brine-3rd", "3rd interview", -7),
      event("brine-sentiment", "sentiment", -6, {
        title: `Sentiment — ${prettySentiment("bad")}`,
        note: "Panel talked over the design critique.",
      }),
    ],
    fit: 2,
    appliedDate: offset(-40),
    followUpDate: "",
    nextAction: "",
    fitEvidence: "",
    risks: "Culture felt hierarchical; no next move recorded.",
    learning: "",
  },
  {
    id: "marrow-health",
    company: "Marrow Health",
    role: "Product Designer",
    jobUrl: "https://marrow.example/roles/product-designer",
    state: "active",
    currentStage: "test task",
    sentiment: "good",
    timeline: [
      event("marrow-applied", "applied", -16),
      event("marrow-1st", "1st interview", -10),
      event("marrow-task", "test task", -2, {
        note: "48-hour clinic intake redesign.",
      }),
    ],
    fit: 4,
    appliedDate: offset(-16),
    followUpDate: offset(0),
    nextAction: "Submit the test task by end of day",
    fitEvidence: "Clinical workflows, accessibility, regulated copy.",
    risks: "Take-home is unpaid and tightly timed.",
    learning: "Ask for a scoped prompt before agreeing to 48 hours.",
  },
  {
    id: "quilt-transit",
    company: "Quilt Transit",
    role: "Product Design Lead",
    jobUrl: "https://quilttransit.example/jobs/design-lead",
    state: "active",
    currentStage: "final round",
    sentiment: "good",
    timeline: [
      event("quilt-applied", "applied", -35),
      event("quilt-1st", "1st interview", -27),
      event("quilt-2nd", "2nd interview", -19),
      event("quilt-3rd", "3rd interview", -12),
      event("quilt-final", "final round", -2),
    ],
    fit: 5,
    appliedDate: offset(-35),
    followUpDate: offset(5),
    nextAction: "Prepare the leadership presentation",
    fitEvidence: "Public-sector adjacent, multi-surface design org.",
    risks: "Comp band unpublished.",
    learning: "",
  },
  {
    id: "orchid-pay",
    company: "Orchid Pay",
    role: "Staff Product Designer",
    jobUrl: "https://orchidpay.example/careers/staff-designer",
    state: "active",
    currentStage: "offer",
    sentiment: "good",
    timeline: [
      event("orchid-applied", "applied", -45),
      event("orchid-1st", "1st interview", -38),
      event("orchid-task", "test task", -30),
      event("orchid-final", "final round", -14),
      event("orchid-offer", "offer", -2),
    ],
    fit: 5,
    appliedDate: offset(-45),
    followUpDate: offset(3),
    nextAction: "Reply on equity and start date",
    fitEvidence: "Fintech onboarding, risk states, high craft.",
    risks: "Offer expires quickly.",
    learning: "",
  },
  {
    id: "vellum-studio",
    company: "Vellum Studio",
    role: "Visual Designer",
    jobUrl: "https://vellum.example/jobs/visual-designer",
    state: "on_hold",
    currentStage: "1st interview",
    sentiment: "neutral",
    timeline: [
      event("vellum-applied", "applied", -22),
      event("vellum-1st", "1st interview", -11),
      event("vellum-hold", "on_hold", -4),
    ],
    fit: 3,
    appliedDate: offset(-22),
    followUpDate: offset(21),
    nextAction: "Wait for the freeze to lift",
    fitEvidence: "Brand-to-product motion, marketing site system.",
    risks: "Hiring freeze with no date.",
    learning: "On hold is not a next action.",
  },
  {
    id: "ashgrove",
    company: "Ashgrove",
    role: "Product Designer",
    jobUrl: "",
    state: "on_hold",
    currentStage: "applied",
    sentiment: "bad",
    timeline: [
      event("ashgrove-applied", "applied", -9),
      event("ashgrove-hold", "on_hold", -1, {
        note: "Reorg paused all IC design hiring.",
      }),
    ],
    fit: 1,
    appliedDate: offset(-9),
    followUpDate: "",
    nextAction: "",
    fitEvidence: "",
    risks: "Speculative apply; no job URL.",
    learning: "",
  },
  {
    id: "copperline",
    company: "Copperline",
    role: "Senior Product Designer",
    jobUrl: "https://copperline.example/jobs/senior-pd",
    state: "closed",
    currentStage: "2nd interview",
    sentiment: "bad",
    outcome: "rejected",
    timeline: [
      event("copper-applied", "applied", -50),
      event("copper-1st", "1st interview", -41),
      event("copper-2nd", "2nd interview", -33),
      event("copper-closed", "closed", -31, {
        title: `Closed — ${prettyOutcome("rejected")}`,
      }),
    ],
    fit: 4,
    appliedDate: offset(-50),
    followUpDate: "",
    nextAction: "",
    fitEvidence: "Industrial IoT dashboards.",
    risks: "They wanted domain experts only.",
    learning: "Ask about domain must-haves before the second round.",
  },
  {
    id: "fogfern",
    company: "Fogfern",
    role: "Product Designer",
    jobUrl: "",
    state: "closed",
    currentStage: "applied",
    sentiment: "neutral",
    outcome: "withdrawn",
    timeline: [
      event("fog-applied", "applied", -18),
      event("fog-closed", "closed", -15, {
        title: `Closed — ${prettyOutcome("withdrawn")}`,
        note: "Withdrew after the salary band was posted.",
      }),
    ],
    fit: 3,
    appliedDate: offset(-18),
    followUpDate: "",
    nextAction: "",
    fitEvidence: "Consumer journaling app.",
    risks: "Comp well below target.",
    learning: "Withdraw early when the band is a hard miss.",
  },
  {
    id: "redthread",
    company: "Redthread",
    role: "Staff Product Designer",
    jobUrl: "https://redthread.example/careers/staff-pd",
    state: "closed",
    currentStage: "1st interview",
    sentiment: "bad",
    outcome: "ghosted",
    timeline: [
      event("red-applied", "applied", -60),
      event("red-1st", "1st interview", -48),
      event("red-closed", "closed", -20, {
        title: `Closed — ${prettyOutcome("ghosted")}`,
      }),
    ],
    fit: 2,
    appliedDate: offset(-60),
    followUpDate: "",
    nextAction: "",
    fitEvidence: "AI writing tools, thin product story.",
    risks: "Recruiter went silent after the screen.",
    learning: "Two follow-ups, then close as ghosted.",
  },
  {
    id: "lumenbox",
    company: "Lumenbox",
    role: "UX Designer",
    jobUrl: "",
    state: "closed",
    currentStage: "applied",
    sentiment: "neutral",
    outcome: "no_response",
    timeline: [
      event("lumen-applied", "applied", -37),
      event("lumen-closed", "closed", -16, {
        title: `Closed — ${prettyOutcome("no_response")}`,
      }),
    ],
    fit: 1,
    appliedDate: offset(-37),
    followUpDate: "",
    nextAction: "",
    fitEvidence: "",
    risks: "Cold apply, no confirmation email.",
    learning: "",
  },
  {
    id: "sable-maps",
    company: "Sable Maps",
    role: "Product Designer",
    jobUrl: "https://sablemaps.example/jobs/pd",
    state: "closed",
    currentStage: "test task",
    sentiment: "bad",
    outcome: "other",
    timeline: [
      event("sable-applied", "applied", -26),
      event("sable-task", "test task", -19),
      event("sable-closed", "closed", -17, {
        title: `Closed — ${prettyOutcome("other")}`,
        note: "Role cancelled after a reorg.",
      }),
    ],
    fit: 3,
    appliedDate: offset(-26),
    followUpDate: "",
    nextAction: "",
    fitEvidence: "Mapping, offline-first field tools.",
    risks: "Req was never backfilled.",
    learning: "Treat cancelled reqs as closed, not stalled.",
  },
  {
    id: "wick-and-co",
    company: "Wick & Co",
    role: "Senior Product Designer",
    jobUrl: "",
    state: "active",
    currentStage: "applied",
    sentiment: "neutral",
    timeline: [event("wick-applied", "applied", -6)],
    fit: 1,
    appliedDate: offset(-6),
    followUpDate: offset(10),
    nextAction: "",
    fitEvidence: "",
    risks: "Stretch role, no public listing.",
    learning: "",
  },
  {
    id: "halo-draft",
    company: "Halo Draft",
    role: "Product Designer",
    jobUrl: "https://halodraft.example/jobs/product-designer",
    state: "active",
    currentStage: "3rd interview",
    sentiment: "good",
    timeline: [
      event("halo-applied", "applied", -21),
      event("halo-1st", "1st interview", -14),
      event("halo-2nd", "2nd interview", -8),
      event("halo-3rd", "3rd interview", -1),
    ],
    fit: 4,
    appliedDate: offset(-21),
    followUpDate: offset(14),
    nextAction: "waiting for response",
    fitEvidence: "Docs product, collaboration, comments and review.",
    risks: "Four more interviewers still unnamed.",
    learning: "",
  },
];
